data1<- read.csv("nm-logit.csv", header = TRUE)
data1
attach(data1)
names(data1)
Y<- as.matrix(data1[,2])
X = as.matrix(data1[,3:5])
model<- glm(Y~X,data = data1,family = binomial)
summary(model)
library(lmtest)
lrtest(model)
library(ps)
install.packages("pscl")
library(pscl)
pR2(model)
logit
confint(model)
exp(coef(model))
exp(confint(model))
library(Deducer)
rocplot(model)
predict(model, type = "response")
pred<- fitted(logit)
data.frame(Loyalty,pred)
gg1 <- floor(pred + 0.5)
table(Actual = Loyalty, Prediction = gg1)
